# Generated by Django 5.2.6 on 2025-09-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pin',
            name='lng',
            field=models.FloatField(),
        ),
    ]
