# Generated by Django 5.2.6 on 2025-09-24 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0003_pin_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='tags',
        ),
        migrations.AddField(
            model_name='pin',
            name='confirmations_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='pin',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending review'), ('disputed', 'Disputed'), ('removed', 'Removed')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='pin',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='pins.pin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_confirmations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['pin', 'user'], name='pins_confir_pin_id_6cf6f0_idx')],
                'unique_together': {('pin', 'user')},
            },
        ),
    ]
